import glob
import json
import os
import pandas as pd

def aggregate_results():
    # Discover all JSON artifacts generated by benchmark.py
    json_paths = glob.glob("results/*.json")
    
    if not json_paths:
        print("⚠️ No benchmark results found. Please check your results/ directory.")
        return

    all_results = []
    for path in json_paths:
        if "summary_matrix" in path:
            continue
        with open(path, "r") as f:
            try:
                data = json.load(f)
                all_results.append(data)
            except json.JSONDecodeError:
                continue

    # Convert payloads into a clean structured table
    df = pd.DataFrame(all_results)
    
    # Sort logically for professional, readable presentation
    df = df.sort_values(by=["dataset", "noise_type", "severity", "model"])
    
    # Format floating numbers for clean viewing
    df["mean_mae"] = df["mean_mae"].round(4)
    df["mean_mse"] = df["mean_mse"].round(4)

    # 1. Output a beautiful Markdown table directly to the console
    print("\n" + "="*70)
    print("🎯 SYSTEM ROBUSTNESS & DRIFT BENCHMARK RESULTS MATRIX")
    print("="*70 + "\n")
    print(df[["dataset", "model", "noise_type", "severity", "mean_mae", "mean_mse"]].to_markdown(index=False))
    print("\n" + "="*70)

    # 2. Persist the matrix to a file so it can be directly copied into your README
    os.makedirs("results", exist_ok=True)
    summary_path = "results/summary_matrix.md"
    with open(summary_path, "w") as f:
        f.write("# 📊 Compiled Performance Metrics\n\n")
        f.write("This table contains the automated robustness mapping across all model architectures.\n\n")
        f.write(df[["dataset", "model", "noise_type", "severity", "mean_mae", "mean_mse"]].to_markdown(index=False))
    print(f"💾 Report compiled and written to: {summary_path}")

if __name__ == "__main__":
    aggregate_results()
